title: "Tate Kennington"
subtitle: ""
description: ""
collections:
  projects:
    output: true
menu:
  - text: Home
    link: /
    icon:
  - text: Portfolio
    link: /portfolio
    icon:
  - text: Blog
    link: /blog
    icon:
url: https://tatekennington.com